//
// This file was auto-generated by a tool.  Do not modify.
//
using System.Resources;
using System.Reflection;

[assembly: NeutralResourcesLanguageAttribute("en-US" , UltimateResourceFallbackLocation.MainAssembly)]
[assembly: AssemblyTitleAttribute("Title Animator")]
[assembly: AssemblyDescriptionAttribute("A WPF Title Animator that displays text through a film-style animation")]
[assembly: AssemblyCompanyAttribute("Nicholas Armstrong")]
[assembly: AssemblyCopyrightAttribute("http://creativecommons.org/licenses/by-sa/2.5/ca/deed.en_CA")]
[assembly: AssemblyTrademarkAttribute("Created August 2007 by Nicholas Armstrong")]
[assembly: AssemblyVersionAttribute("1.0.0")]
